global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['172.17.0.1:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s